### ISSUE TITLE
Docker builds failing since 3.1.0

### ISSUE THREAD

**Issue by Crayjin** [ciricihq/gitlab-sonar-scanner#39]
As you can see here (https://hub.docker.com/r/ciricihq/gitlab-sonar-scanner/builds) the Docker builds are failing.
A local test shows that the Dockerfile cannot find the required ZIP file on line 6. Not sure if you just can replace the URI with the following one as it may change in the future:

https://dl.bintray.com/sonarsource/SonarQube/org/sonarsource/scanner/cli/sonar-scanner-cli/${SONAR_SCANNER_VERSION}/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip

**Comment by elboletaire** [comment]
I'm trying to figure out which is the proper download link now, because I've found multiple sources and they have files with the exact same name, but different sizes.

- Here at github you can find it at https://github.com/SonarSource/sonar-scanner-cli but its cli filesize is less than 200KB
- From bintray, which is the source which we were using before https://bintray.com/sonarsource/SonarQube/org.sonarsource.scanner.cli, where it has a size of ~ 500KB 

I don't really care about the size, but it makes me think they are totally different tools although they're named equally.

I'll do some tests and try to update the image as soon as I find the actual client.
